### ISSUE TITLE
Still experimental? Or deprecated?

### ISSUE THREAD

**Issue by coolaj86** [mre/cargo-ship#1]
> It's still experimental and will only work once/if Rust support gets added to goreleaser.

As per https://github.com/goreleaser/goreleaser/issues/496#issuecomment-359209326 it looks like this support was added via https://github.com/goreleaser/goreleaser/pull/522

Is `cargo deliver` now ready for prime-time? Or is there an updated method?

cc/ @andygrunwald

**Comment by coolaj86** [comment]
Looks like https://github.com/sunng87/cargo-release is the new hotness?

**Comment by andygrunwald** [comment]
@coolaj86 This project was a prototype and never went fully into implementation.
@mre and I are not working on this anymore. Sorry.

Not 100% sure what the current state of Rust + goeleaser is. As far as I remember, the linked PR only sets the foundation to build multiple languages.

In the goreleaser docs, there is this tutorial listed: https://medium.com/@jondot/shipping-rust-binaries-with-goreleaser-d5aa42a46be0
Not sure how complete this is. This might help you.

**Comment by mre** [comment]
> Looks like https://github.com/sunng87/cargo-release is the new hotness?

Very much yes. A lot has improved in the Rust ecosystem that allowed that push forward. cargo-release is superior in every way. 😄

**Comment by coolaj86** [comment]
> cargo-release is superior in every way.

Really? I didn't see anything about cross-platform builds.

I'll open back my Deprecation notice PR then.

**Comment by mre** [comment]
Ouch, sorry I was mixing this up. You're right, it's not the same scope.
Goreleaser might not see proper Rust support anytime soon according to 
https://github.com/goreleaser/goreleaser/issues/1787

Thought there was an alternative tool but I can't find it anymore.
Your best bet might still be https://medium.com/@jondot/shipping-rust-binaries-with-goreleaser-d5aa42a46be0
Sorry for the confusion.
